const mongoose = require('mongoose')

const Schema = mongoose.Schema
const stockSchema = Schema({
    assetType: {type: String},
    assetMainType: {type: String},
    cusip: {type: String},
    symbol: {type: String},
    description: {type: String},
    bidPrice: {type: String},
    bidSize: {type: String},
    bidId: {type: String},
    askPrice: {type: String},
    askSize: {type: String},
    askId: {type: String},
    lastPrice: {type: String},
    lastSize: {type: String},
    lastId: {type: String},
    openPrice: {type: String},
    highPrice: {type: String},
    lowPrice: {type: String},
    bidTick: {type: String},
    closePrice: {type: String},
    netChange: {type: String},
    totalVolume: {type: String},
    quoteTimeInLong: {type: String},
    tradeTimeInLong: {type: String},
    mark: {type: String},
    exchange: {type: String},
    exchangeName: {type: String},
    marginable: {type: String},
    shortable: {type: String},
    volatility: {type: String},
    digits: {type: String},
    yearHigh: {type: String},
    yearLow: {type: String},
    nAV: {type: String},
    peRatio: {type: String},
    divAmount: {type: String},
    divYield: {type: String},
    divDate: {type: String},
    securityStatus: {type: String},
    regularMarketLastPrice: {type: String},
    regularMarketLastSize: {type: String},
    regularMarketNetChange: {type: String},
    regularMarketTradeTimeInLong: {type: String},
    netPercentChangeInDouble: {type: String},
    markChangeInDouble: {type: String},
    markPercentChangeInDouble: {type: String},
    regularMarketPercentChangeInDouble: {type: String},
    delayed: {type: String},
}, {timestamps: true})
const Stock = mongoose.model('Stock', stockSchema)
module.exports = Stock